export const reportedCases = [
    {
      reportDate: "2023-10-02",
      reportTime: "09:45",
      incidentDate: "2023-10-02",
      incidentTime: "08:00",
      position: "Detective",
      firstName: "Jane",
      middleName: "B.",
      lastName: "Smith",
      location: "Downtown, Los Angeles",
      details: "A robbery occurred at a jewelry store.",
      suspectDetails: "Suspect was wearing a black mask and gloves.",
      arrestDetails: "One suspect arrested.",
      suspectFirstName: "Michael",
      suspectLastName: "Brown",
      contactInfo: "jane.smith@example.com",
      mediaFile: "file://path/to/media/file2.jpg",
      certified: true,
    },
    {
      reportDate: "2023-10-03",
      reportTime: "16:20",
      incidentDate: "2023-10-03",
      incidentTime: "15:00",
      position: "Officer",
      firstName: "David",
      middleName: "C.",
      lastName: "Johnson",
      location: "Times Square, New York",
      details: "A pickpocketing incident reported.",
      suspectDetails: "Suspect was seen wearing a blue jacket.",
      arrestDetails: "No arrests made yet.",
      suspectFirstName: "Unknown",
      suspectLastName: "",
      contactInfo: "david.johnson@example.com",
      mediaFile: "file://path/to/media/file3.jpg",
      certified: true,
    },
    {
      reportDate: "2023-10-04",
      reportTime: "11:10",
      incidentDate: "2023-10-04",
      incidentTime: "10:00",
      position: "Sergeant",
      firstName: "Emily",
      middleName: "D.",
      lastName: "Davis",
      location: "Union Station, Chicago",
      details: "A bag was stolen from a passenger.",
      suspectDetails: "Suspect was wearing a gray hoodie.",
      arrestDetails: "Suspect fled the scene.",
      suspectFirstName: "Unknown",
      suspectLastName: "",
      contactInfo: "emily.davis@example.com",
      mediaFile: "file://path/to/media/file4.jpg",
      certified: true,
    },
    {
      reportDate: "2023-10-05",
      reportTime: "13:50",
      incidentDate: "2023-10-05",
      incidentTime: "12:30",
      position: "Officer",
      firstName: "Robert",
      middleName: "E.",
      lastName: "Wilson",
      location: "Golden Gate Park, San Francisco",
      details: "A bike theft was reported near the entrance.",
      suspectDetails: "Suspect was seen carrying a backpack.",
      arrestDetails: "No arrests made yet.",
      suspectFirstName: "Unknown",
      suspectLastName: "",
      contactInfo: "robert.wilson@example.com",
      mediaFile: "file://path/to/media/file5.jpg",
      certified: true,
    },
    {
      reportDate: "2023-10-06",
      reportTime: "08:30",
      incidentDate: "2023-10-06",
      incidentTime: "07:00",
      position: "Detective",
      firstName: "Sarah",
      middleName: "F.",
      lastName: "Martinez",
      location: "Hollywood Boulevard, Los Angeles",
      details: "A car break-in was reported.",
      suspectDetails: "Suspect was wearing sunglasses.",
      arrestDetails: "Suspect escaped on foot.",
      suspectFirstName: "Unknown",
      suspectLastName: "",
      contactInfo: "sarah.martinez@example.com",
      mediaFile: "file://path/to/media/file6.jpg",
      certified: true,
    },
    {
      reportDate: "2023-10-07",
      reportTime: "15:45",
      incidentDate: "2023-10-07",
      incidentTime: "14:00",
      position: "Officer",
      firstName: "James",
      middleName: "G.",
      lastName: "Anderson",
      location: "Central Park, New York",
      details: "A fight broke out near the playground.",
      suspectDetails: "Two suspects involved, one in a red shirt.",
      arrestDetails: "Both suspects detained.",
      suspectFirstName: "Mark",
      suspectLastName: "Taylor",
      contactInfo: "james.anderson@example.com",
      mediaFile: "file://path/to/media/file7.jpg",
      certified: true,
    },
    {
      reportDate: "2023-10-08",
      reportTime: "10:20",
      incidentDate: "2023-10-08",
      incidentTime: "09:00",
      position: "Sergeant",
      firstName: "Laura",
      middleName: "H.",
      lastName: "Thomas",
      location: "Michigan Avenue, Chicago",
      details: "A purse snatching incident occurred.",
      suspectDetails: "Suspect was wearing a green cap.",
      arrestDetails: "No arrests made yet.",
      suspectFirstName: "Unknown",
      suspectLastName: "",
      contactInfo: "laura.thomas@example.com",
      mediaFile: "file://path/to/media/file8.jpg",
      certified: true,
    },
    {
      reportDate: "2023-10-09",
      reportTime: "12:30",
      incidentDate: "2023-10-09",
      incidentTime: "11:00",
      position: "Officer",
      firstName: "Daniel",
      middleName: "I.",
      lastName: "Lee",
      location: "Fisherman's Wharf, San Francisco",
      details: "A wallet was stolen from a tourist.",
      suspectDetails: "Suspect was wearing a leather jacket.",
      arrestDetails: "Suspect fled on a motorcycle.",
      suspectFirstName: "Unknown",
      suspectLastName: "",
      contactInfo: "daniel.lee@example.com",
      mediaFile: "file://path/to/media/file9.jpg",
      certified: true,
    },
    {
      reportDate: "2023-10-10",
      reportTime: "14:10",
      incidentDate: "2023-10-10",
      incidentTime: "13:00",
      position: "Detective",
      firstName: "Jessica",
      middleName: "J.",
      lastName: "White",
      location: "Brooklyn Bridge, New York",
      details: "A phone was stolen from a pedestrian.",
      suspectDetails: "Suspect was wearing a black hoodie.",
      arrestDetails: "No arrests made yet.",
      suspectFirstName: "Unknown",
      suspectLastName: "",
      contactInfo: "jessica.white@example.com",
      mediaFile: "file://path/to/media/file10.jpg",
      certified: true,
    },
    {
      reportDate: "2023-10-11",
      reportTime: "09:40",
      incidentDate: "2023-10-11",
      incidentTime: "08:30",
      position: "Officer",
      firstName: "Michael",
      middleName: "K.",
      lastName: "Harris",
      location: "Venice Beach, Los Angeles",
      details: "A bicycle was stolen from a stand.",
      suspectDetails: "Suspect was seen with a backpack.",
      arrestDetails: "No arrests made yet.",
      suspectFirstName: "Unknown",
      suspectLastName: "",
      contactInfo: "michael.harris@example.com",
      mediaFile: "file://path/to/media/file11.jpg",
      certified: true,
    },
    {
      reportDate: "2023-10-12",
      reportTime: "11:50",
      incidentDate: "2023-10-12",
      incidentTime: "10:30",
      position: "Sergeant",
      firstName: "Sophia",
      middleName: "L.",
      lastName: "Clark",
      location: "Navy Pier, Chicago",
      details: "A bag was stolen from a visitor.",
      suspectDetails: "Suspect was wearing a striped shirt.",
      arrestDetails: "Suspect escaped on foot.",
      suspectFirstName: "Unknown",
      suspectLastName: "",
      contactInfo: "sophia.clark@example.com",
      mediaFile: "file://path/to/media/file12.jpg",
      certified: true,
    },
    {
      reportDate: "2023-10-13",
      reportTime: "13:20",
      incidentDate: "2023-10-13",
      incidentTime: "12:00",
      position: "Officer",
      firstName: "Matthew",
      middleName: "M.",
      lastName: "Lewis",
      location: "Alcatraz Island, San Francisco",
      details: "A camera was stolen from a tourist.",
      suspectDetails: "Suspect was wearing a baseball cap.",
      arrestDetails: "No arrests made yet.",
      suspectFirstName: "Unknown",
      suspectLastName: "",
      contactInfo: "matthew.lewis@example.com",
      mediaFile: "file://path/to/media/file13.jpg",
      certified: true,
    },
    {
      reportDate: "2023-10-14",
      reportTime: "15:10",
      incidentDate: "2023-10-14",
      incidentTime: "14:00",
      position: "Detective",
      firstName: "Olivia",
      middleName: "N.",
      lastName: "Walker",
      location: "Statue of Liberty, New York",
      details: "A wallet was stolen from a visitor.",
      suspectDetails: "Suspect was wearing a denim jacket.",
      arrestDetails: "No arrests made yet.",
      suspectFirstName: "Unknown",
      suspectLastName: "",
      contactInfo: "olivia.walker@example.com",
      mediaFile: "file://path/to/media/file14.jpg",
      certified: true,
    },
    {
      reportDate: "2023-10-15",
      reportTime: "10:30",
      incidentDate: "2023-10-15",
      incidentTime: "09:00",
      position: "Officer",
      firstName: "William",
      middleName: "O.",
      lastName: "Hall",
      location: "Santa Monica Pier, Los Angeles",
      details: "A phone was stolen from a tourist.",
      suspectDetails: "Suspect was wearing a red cap.",
      arrestDetails: "No arrests made yet.",
      suspectFirstName: "Unknown",
      suspectLastName: "",
      contactInfo: "william.hall@example.com",
      mediaFile: "file://path/to/media/file15.jpg",
      certified: true,
    },
    {
      reportDate: "2023-10-16",
      reportTime: "12:45",
      incidentDate: "2023-10-16",
      incidentTime: "11:30",
      position: "Sergeant",
      firstName: "Ava",
      middleName: "P.",
      lastName: "Allen",
      location: "Millennium Park, Chicago",
      details: "A bag was stolen from a visitor.",
      suspectDetails: "Suspect was wearing a yellow shirt.",
      arrestDetails: "No arrests made yet.",
      suspectFirstName: "Unknown",
      suspectLastName: "",
      contactInfo: "ava.allen@example.com",
      mediaFile: "file://path/to/media/file16.jpg",
      certified: true,
    },
    {
      reportDate: "2023-10-17",
      reportTime: "14:30",
      incidentDate: "2023-10-17",
      incidentTime: "13:00",
      position: "Officer",
      firstName: "Ethan",
      middleName: "Q.",
      lastName: "Young",
      location: "Chinatown, San Francisco",
      details: "A purse was stolen from a shopper.",
      suspectDetails: "Suspect was wearing a black jacket.",
      arrestDetails: "No arrests made yet.",
      suspectFirstName: "Unknown",
      suspectLastName: "",
      contactInfo: "ethan.young@example.com",
      mediaFile: "file://path/to/media/file17.jpg",
      certified: true,
    },
    {
      reportDate: "2023-10-18",
      reportTime: "09:10",
      incidentDate: "2023-10-18",
      incidentTime: "08:00",
      position: "Detective",
      firstName: "Isabella",
      middleName: "R.",
      lastName: "King",
      location: "Empire State Building, New York",
      details: "A wallet was stolen from a tourist.",
      suspectDetails: "Suspect was wearing a gray hoodie.",
      arrestDetails: "No arrests made yet.",
      suspectFirstName: "Unknown",
      suspectLastName: "",
      contactInfo: "isabella.king@example.com",
      mediaFile: "file://path/to/media/file18.jpg",
      certified: true,
    },
    {
      reportDate: "2023-10-19",
      reportTime: "11:20",
      incidentDate: "2023-10-19",
      incidentTime: "10:00",
      position: "Officer",
      firstName: "Liam",
      middleName: "S.",
      lastName: "Scott",
      location: "Griffith Observatory, Los Angeles",
      details: "A phone was stolen from a visitor.",
      suspectDetails: "Suspect was wearing a blue cap.",
      arrestDetails: "No arrests made yet.",
      suspectFirstName: "Unknown",
      suspectLastName: "",
      contactInfo: "liam.scott@example.com",
      mediaFile: "file://path/to/media/file19.jpg",
      certified: true,
    },
    {
      reportDate: "2023-10-20",
      reportTime: "13:40",
      incidentDate: "2023-10-20",
      incidentTime: "12:30",
      position: "Sergeant",
      firstName: "Mia",
      middleName: "T.",
      lastName: "Green",
      location: "Lincoln Park, Chicago",
      details: "A bag was stolen from a jogger.",
      suspectDetails: "Suspect was wearing a white t-shirt.",
      arrestDetails: "No arrests made yet.",
      suspectFirstName: "Unknown",
      suspectLastName: "",
      contactInfo: "mia.green@example.com",
      mediaFile: "file://path/to/media/file20.jpg",
      certified: true,
    },
    {
      reportDate: "2023-10-21",
      reportTime: "15:30",
      incidentDate: "2023-10-21",
      incidentTime: "14:00",
      position: "Officer",
      firstName: "Noah",
      middleName: "U.",
      lastName: "Adams",
      location: "Mission District, San Francisco",
      details: "A wallet was stolen from a restaurant.",
      suspectDetails: "Suspect was wearing a black hoodie.",
      arrestDetails: "No arrests made yet.",
      suspectFirstName: "Unknown",
      suspectLastName: "",
      contactInfo: "noah.adams@example.com",
      mediaFile: "file://path/to/media/file21.jpg",
      certified: true,
    },
    {
      reportDate: "2023-10-22",
      reportTime: "10:50",
      incidentDate: "2023-10-22",
      incidentTime: "09:30",
      position: "Detective",
      firstName: "Charlotte",
      middleName: "V.",
      lastName: "Wright",
      location: "Grand Central Terminal, New York",
      details: "A phone was stolen from a commuter.",
      suspectDetails: "Suspect was wearing a red jacket.",
      arrestDetails: "No arrests made yet.",
      suspectFirstName: "Unknown",
      suspectLastName: "",
      contactInfo: "charlotte.wright@example.com",
      mediaFile: "file://path/to/media/file22.jpg",
      certified: true,
    },
    {
      reportDate: "2023-10-23",
      reportTime: "12:10",
      incidentDate: "2023-10-23",
      incidentTime: "11:00",
      position: "Officer",
      firstName: "Lucas",
      middleName: "W.",
      lastName: "Evans",
      location: "The Getty Center, Los Angeles",
      details: "A camera was stolen from a tourist.",
      suspectDetails: "Suspect was wearing a green hoodie.",
      arrestDetails: "No arrests made yet.",
      suspectFirstName: "Unknown",
      suspectLastName: "",
      contactInfo: "lucas.evans@example.com",
      mediaFile: "file://path/to/media/file23.jpg",
      certified: true,
    },
    {
      reportDate: "2023-10-24",
      reportTime: "14:20",
      incidentDate: "2023-10-24",
      incidentTime: "13:00",
      position: "Sergeant",
      firstName: "Amelia",
      middleName: "X.",
      lastName: "Baker",
      location: "Art Institute, Chicago",
      details: "A bag was stolen from a visitor.",
      suspectDetails: "Suspect was wearing a black cap.",
      arrestDetails: "No arrests made yet.",
      suspectFirstName: "Unknown",
      suspectLastName: "",
      contactInfo: "amelia.baker@example.com",
      mediaFile: "file://path/to/media/file24.jpg",
      certified: true,
    },
    {
      reportDate: "2023-10-25",
      reportTime: "16:30",
      incidentDate: "2023-10-25",
      incidentTime: "15:00",
      position: "Officer",
      firstName: "Henry",
      middleName: "Y.",
      lastName: "Murphy",
      location: "Presidio, San Francisco",
      details: "A phone was stolen from a hiker.",
      suspectDetails: "Suspect was wearing a blue hoodie.",
      arrestDetails: "No arrests made yet.",
      suspectFirstName: "Unknown",
      suspectLastName: "",
      contactInfo: "henry.murphy@example.com",
      mediaFile: "file://path/to/media/file25.jpg",
      certified: true,
    },
]